### PR TITLE
Add support for sparkpost smtp

### PR DESCRIPTION
**Pull request by mbrostami**

### CODE REVIEW

**Comment by petemcw** [comment]
Sorry, all this PR activity was buried in my notifications. If you're still interested push an updated PR, otherwise I can close this one.

**Comment by mbrostami** [comment]
@petemcw May you please review the code?

**Comment by robbyoconnor** [comment]
@mbrostami -- you should rebase and squash.

**Comment by robbyoconnor** [comment]
I rebased this in #13  for @mbrostami and have tested this. I am using it currently.

**Pull request closed without merging**
